name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: runner.os == 'Linux'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: fonxy6
          password: dckr_pat_HgxTTHJm4Afokj4NKNcof4OJFlM

      - name: List files in context
        run: ls -R

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: fonxy6/solarwatch:latest
          dockerfile: SolarWatchMvp/SolarWatchMvp/Dockerfile
