# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: D:/codecool/solarwatch/SolarWatchMvp
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SolarWatchMvp.csproj
    - name: Build
      run: dotnet build --no-restore SolarWatchMvp.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal SolarWatchMvp.csproj
